### PR TITLE
Bump versions & remove unused dependencies

### PR DESCRIPTION
**Pull request by black-puppydog**
There was a bunch of cruft left around from older versions.

### CODE REVIEW

**Comment by black-puppydog** [comment]
Could also use a version bump & npm publish when there's time.

**Comment by arj03** [comment]
Looks good! :) Please merge, I see you are in SSBC so you should be able to merge and do a new version. Do you have access to NPM?

**Comment by black-puppydog** [comment]
I can merge, yes, but I don't think I'm on npm and frankly the npm release mechanisms are not something I've used more than once. Check out my mad npm creds: https://www.npmjs.com/~dwynen

* no orgs
* only one package and that's a debug tryout thingy polluting the common namespace
* not even a profile picture 😎

**Comment by black-puppydog** [comment]
(but ofc I can learn that, no worries. I think it's mostly a single command for this kind of package anyhow, right?)

**Comment by arj03** [comment]
Published as 1.0.3

**Comment by arj03** [comment]
No dice, I don't have permission to publish to npm :(

**Pull request merged**
